codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%

ignore:
  - "test/**/*"
  - "app/**/*"
  - "dist/**/*"
  - "bin/**/*"
  - "**/*.test.ts"
  - "src/cli/help.ts"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
