packages:
  - app
  - packages/*

verifyDepsBeforeRun: false

onlyBuiltDependencies:
  - esbuild
  - scriptc

ignoredBuiltDependencies:
  - es5-ext
allowBuilds:
  es5-ext: false
  esbuild: true
  scriptc: true
