import type { Method } from "./types";

export const ARRAY_METHODS: Method[] = [
  {
    name: "map",
    signature: ".map(x => ...)",
    description: "Transform each item",
    template: ".map(x => x)",
    category: "Transform",
  },
  {
    name: "filter",
    signature: ".filter(x => ...)",
    description: "Filter by condition",
    template: ".filter(x => x)",
    category: "Filter",
  },
  {
    name: "reduce",
    signature: ".reduce((acc, x) => ..., initial)",
    description: "Reduce to single value",
    template: ".reduce((acc, x) => acc, 0)",
    category: "Aggregate",
  },
  {
    name: "find",
    signature: ".find(x => ...)",
    description: "Find first match",
    template: ".find(x => x)",
    category: "Search",
  },
  {
    name: "findIndex",
    signature: ".findIndex(x => ...)",
    description: "Find first match index",
    template: ".findIndex(x => x)",
    category: "Search",
  },
  {
    name: "some",
    signature: ".some(x => ...)",
    description: "Check if any match",
    template: ".some(x => x)",
    category: "Test",
  },
  {
    name: "every",
    signature: ".every(x => ...)",
    description: "Check if all match",
    template: ".every(x => x)",
    category: "Test",
  },
  {
    name: "sort",
    signature: ".sort((a, b) => ...)",
    description: "Sort items",
    template: ".sort((a, b) => a - b)",
    category: "Transform",
  },
  {
    name: "reverse",
    signature: ".reverse()",
    description: "Reverse order",
    template: ".reverse()",
    category: "Transform",
  },
  {
    name: "slice",
    signature: ".slice(start, end)",
    description: "Get subset",
    template: ".slice(0, 10)",
    category: "Transform",
  },
  {
    name: "concat",
    signature: ".concat(arr)",
    description: "Combine arrays",
    template: ".concat([])",
    category: "Transform",
  },
  {
    name: "join",
    signature: ".join(separator)",
    description: "Join to string",
    template: ".join(', ')",
    category: "Convert",
  },
  {
    name: "flat",
    signature: ".flat(depth)",
    description: "Flatten nested arrays",
    template: ".flat(1)",
    category: "Transform",
  },
  {
    name: "flatMap",
    signature: ".flatMap(x => ...)",
    description: "Map then flatten",
    template: ".flatMap(x => x)",
    category: "Transform",
  },
  {
    name: "length",
    signature: ".length",
    description: "Get array length",
    template: ".length",
    category: "Property",
  },
];

export const STRING_METHODS: Method[] = [
  {
    name: "toUpperCase",
    signature: ".toUpperCase()",
    description: "Convert to uppercase",
    template: ".toUpperCase()",
    category: "Transform",
  },
  {
    name: "toLowerCase",
    signature: ".toLowerCase()",
    description: "Convert to lowercase",
    template: ".toLowerCase()",
    category: "Transform",
  },
  {
    name: "trim",
    signature: ".trim()",
    description: "Remove whitespace",
    template: ".trim()",
    category: "Transform",
  },
  {
    name: "trimStart",
    signature: ".trimStart()",
    description: "Remove leading whitespace",
    template: ".trimStart()",
    category: "Transform",
  },
  {
    name: "trimEnd",
    signature: ".trimEnd()",
    description: "Remove trailing whitespace",
    template: ".trimEnd()",
    category: "Transform",
  },
  {
    name: "split",
    signature: ".split(separator)",
    description: "Split into array",
    template: ".split(',')",
    category: "Convert",
  },
  {
    name: "replace",
    signature: ".replace(search, replace)",
    description: "Replace first match",
    template: ".replace('old', 'new')",
    category: "Transform",
  },
  {
    name: "replaceAll",
    signature: ".replaceAll(search, replace)",
    description: "Replace all matches",
    template: ".replaceAll('old', 'new')",
    category: "Transform",
  },
  {
    name: "substring",
    signature: ".substring(start, end)",
    description: "Extract substring",
    template: ".substring(0, 10)",
    category: "Transform",
  },
  {
    name: "slice",
    signature: ".slice(start, end)",
    description: "Extract slice",
    template: ".slice(0, 10)",
    category: "Transform",
  },
  {
    name: "startsWith",
    signature: ".startsWith(str)",
    description: "Check if starts with",
    template: ".startsWith('prefix')",
    category: "Test",
  },
  {
    name: "endsWith",
    signature: ".endsWith(str)",
    description: "Check if ends with",
    template: ".endsWith('suffix')",
    category: "Test",
  },
  {
    name: "includes",
    signature: ".includes(str)",
    description: "Check if contains",
    template: ".includes('text')",
    category: "Test",
  },
  {
    name: "match",
    signature: ".match(regex)",
    description: "Match regex pattern",
    template: ".match(/pattern/)",
    category: "Search",
  },
  {
    name: "length",
    signature: ".length",
    description: "Get string length",
    template: ".length",
    category: "Property",
  },
];

export const OBJECT_OPERATIONS: Method[] = [
  {
    name: "keys",
    signature: ".{keys}",
    description: "Get object keys",
    template: ".{keys}",
    category: "Convert",
  },
  {
    name: "values",
    signature: ".{values}",
    description: "Get object values",
    template: ".{values}",
    category: "Convert",
  },
  {
    name: "entries",
    signature: ".{entries}",
    description: "Get key-value pairs",
    template: ".{entries}",
    category: "Convert",
  },
  {
    name: "length",
    signature: ".{length}",
    description: "Get property count",
    template: ".{length}",
    category: "Property",
  },
];

export const NUMBER_METHODS: Method[] = [
  {
    name: "toFixed",
    signature: ".toFixed(decimals)",
    description: "Format with decimals",
    template: ".toFixed(2)",
    category: "Format",
  },
  {
    name: "toString",
    signature: ".toString()",
    description: "Convert to string",
    template: ".toString()",
    category: "Convert",
  },
];

export const ARRAY_BUILTINS: Method[] = [
  {
    name: "head",
    signature: "head()",
    description: "First element",
    template: ".head()",
    category: "Access",
    isBuiltin: true,
  },
  {
    name: "last",
    signature: "last()",
    description: "Last element",
    template: ".last()",
    category: "Access",
    isBuiltin: true,
  },
  {
    name: "tail",
    signature: "tail()",
    description: "All but first element",
    template: ".tail()",
    category: "Transform",
    isBuiltin: true,
  },
  {
    name: "take",
    signature: "take(n)",
    description: "First n elements",
    template: ".take(5)",
    category: "Transform",
    isBuiltin: true,
  },
  {
    name: "drop",
    signature: "drop(n)",
    description: "Skip first n elements",
    template: ".drop(5)",
    category: "Transform",
    isBuiltin: true,
  },
  {
    name: "uniq",
    signature: "uniq()",
    description: "Remove duplicates",
    template: ".uniq()",
    category: "Transform",
    isBuiltin: true,
  },
  {
    name: "flatten",
    signature: "flatten()",
    description: "Flatten nested arrays",
    template: ".flatten()",
    category: "Transform",
    isBuiltin: true,
  },
  {
    name: "compact",
    signature: "compact()",
    description: "Remove falsy values",
    template: ".compact()",
    category: "Transform",
    isBuiltin: true,
  },
  {
    name: "chunk",
    signature: "chunk(n)",
    description: "Split into chunks of size n",
    template: ".chunk(3)",
    category: "Transform",
    isBuiltin: true,
  },
  {
    name: "groupBy",
    signature: "groupBy(fn)",
    description: "Group by key function",
    template: ".groupBy(x => x)",
    category: "Aggregate",
    isBuiltin: true,
  },
  {
    name: "sortBy",
    signature: "sortBy(fn)",
    description: "Sort by key function",
    template: ".sortBy(x => x)",
    category: "Transform",
    isBuiltin: true,
  },
  {
    name: "pluck",
    signature: "pluck(key)",
    description: "Extract property from each item",
    template: ".pluck('name')",
    category: "Transform",
    isBuiltin: true,
  },
  {
    name: "sum",
    signature: "sum()",
    description: "Sum of numbers",
    template: ".sum()",
    category: "Aggregate",
    isBuiltin: true,
  },
  {
    name: "mean",
    signature: "mean()",
    description: "Average of numbers",
    template: ".mean()",
    category: "Aggregate",
    isBuiltin: true,
  },
  {
    name: "min",
    signature: "min()",
    description: "Minimum value",
    template: ".min()",
    category: "Aggregate",
    isBuiltin: true,
  },
  {
    name: "max",
    signature: "max()",
    description: "Maximum value",
    template: ".max()",
    category: "Aggregate",
    isBuiltin: true,
  },
  {
    name: "add",
    signature: "add()",
    description: "Sum numbers or concat strings/arrays",
    template: ".add()",
    category: "Aggregate",
    isBuiltin: true,
  },
];

export const OBJECT_BUILTINS: Method[] = [
  {
    name: "keys",
    signature: "keys()",
    description: "Get object keys",
    template: ".keys()",
    category: "Convert",
    isBuiltin: true,
  },
  {
    name: "vals",
    signature: "vals()",
    description: "Get object values",
    template: ".vals()",
    category: "Convert",
    isBuiltin: true,
  },
  {
    name: "pick",
    signature: "pick(k1, k2, ...)",
    description: "Pick specific keys",
    template: ".pick('key1', 'key2')",
    category: "Transform",
    isBuiltin: true,
  },
  {
    name: "omit",
    signature: "omit(k1, k2, ...)",
    description: "Omit specific keys",
    template: ".omit('key1', 'key2')",
    category: "Transform",
    isBuiltin: true,
  },
  {
    name: "merge",
    signature: "merge(obj)",
    description: "Shallow merge objects",
    template: ".merge({})",
    category: "Transform",
    isBuiltin: true,
  },
  {
    name: "toPairs",
    signature: "toPairs()",
    description: "Convert object to pairs",
    template: ".toPairs()",
    category: "Convert",
    isBuiltin: true,
  },
  {
    name: "has",
    signature: "has(key)",
    description: "Check if key exists",
    template: ".has('key')",
    category: "Test",
    isBuiltin: true,
  },
];

export const STRING_BUILTINS: Method[] = [
  {
    name: "split",
    signature: "split(sep)",
    description: "Split string by separator",
    template: ".split(',')",
    category: "Convert",
    isBuiltin: true,
  },
  {
    name: "startswith",
    signature: "startswith(s)",
    description: "Check if starts with string",
    template: ".startswith('prefix')",
    category: "Test",
    isBuiltin: true,
  },
  {
    name: "endswith",
    signature: "endswith(s)",
    description: "Check if ends with string",
    template: ".endswith('suffix')",
    category: "Test",
    isBuiltin: true,
  },
  {
    name: "ltrimstr",
    signature: "ltrimstr(s)",
    description: "Remove prefix",
    template: ".ltrimstr('prefix')",
    category: "Transform",
    isBuiltin: true,
  },
  {
    name: "rtrimstr",
    signature: "rtrimstr(s)",
    description: "Remove suffix",
    template: ".rtrimstr('suffix')",
    category: "Transform",
    isBuiltin: true,
  },
  {
    name: "tostring",
    signature: "tostring()",
    description: "Convert to string",
    template: ".tostring()",
    category: "Convert",
    isBuiltin: true,
  },
];

export const NUMBER_BUILTINS: Method[] = [
  {
    name: "floor",
    signature: "floor()",
    description: "Floor number",
    template: ".floor()",
    category: "Math",
    isBuiltin: true,
  },
  {
    name: "ceil",
    signature: "ceil()",
    description: "Ceiling number",
    template: ".ceil()",
    category: "Math",
    isBuiltin: true,
  },
  {
    name: "round",
    signature: "round()",
    description: "Round number",
    template: ".round()",
    category: "Math",
    isBuiltin: true,
  },
  {
    name: "abs",
    signature: "abs()",
    description: "Absolute value",
    template: ".abs()",
    category: "Math",
    isBuiltin: true,
  },
  {
    name: "tonumber",
    signature: "tonumber()",
    description: "Convert to number",
    template: ".tonumber()",
    category: "Convert",
    isBuiltin: true,
  },
];

export const UNIVERSAL_BUILTINS: Method[] = [
  {
    name: "type",
    signature: "type()",
    description: "Get value type",
    template: ".type()",
    category: "Inspect",
    isBuiltin: true,
  },
  {
    name: "len",
    signature: "len()",
    description: "Get length",
    template: ".len()",
    category: "Inspect",
    isBuiltin: true,
  },
  {
    name: "isEmpty",
    signature: "isEmpty()",
    description: "Check if empty",
    template: ".isEmpty()",
    category: "Test",
    isBuiltin: true,
  },
  {
    name: "isNil",
    signature: "isNil()",
    description: "Check if null/undefined",
    template: ".isNil()",
    category: "Test",
    isBuiltin: true,
  },
  {
    name: "contains",
    signature: "contains(val)",
    description: "Check if contains value",
    template: ".contains(value)",
    category: "Test",
    isBuiltin: true,
  },
];
