import type { Suggestion } from "./types";

export const MAX_SUGGESTIONS = 8;

export const SCORE_PREFIX_MATCH = 100;
export const SCORE_CONTAINS_MATCH = 50;
export const SCORE_FUZZY_MATCH = 25;

export const QUOTE_PATTERN = /['"]([^'"]*\.([a-zA-Z_$][\w$]*)?)$/;
export const DOT_PATTERN = /\.([a-zA-Z_$][\w$]*)?$/;

export const METHODS: Suggestion[] = [
  {
    name: "map",
    signature: ".map(x => ...)",
    description: "Transform each element",
    type: "method",
    insertText: ".map(x => x)",
  },
  {
    name: "filter",
    signature: ".filter(x => ...)",
    description: "Filter by condition",
    type: "method",
    insertText: ".filter(x => x)",
  },
  {
    name: "find",
    signature: ".find(x => ...)",
    description: "Find first match",
    type: "method",
    insertText: ".find(x => x)",
  },
  {
    name: "reduce",
    signature: ".reduce((a,x) => ..., init)",
    description: "Reduce to value",
    type: "method",
    insertText: ".reduce((a, x) => a, 0)",
  },
  {
    name: "some",
    signature: ".some(x => ...)",
    description: "Test if any match",
    type: "method",
    insertText: ".some(x => x)",
  },
  {
    name: "every",
    signature: ".every(x => ...)",
    description: "Test if all match",
    type: "method",
    insertText: ".every(x => x)",
  },
  {
    name: "sort",
    signature: ".sort((a,b) => ...)",
    description: "Sort elements",
    type: "method",
    insertText: ".sort((a, b) => a - b)",
  },
  {
    name: "slice",
    signature: ".slice(start, end)",
    description: "Get subset",
    type: "method",
    insertText: ".slice(0, 10)",
  },
  {
    name: "join",
    signature: ".join(sep)",
    description: "Join to string",
    type: "method",
    insertText: ".join(', ')",
  },
  {
    name: "flat",
    signature: ".flat(depth)",
    description: "Flatten nested",
    type: "method",
    insertText: ".flat(1)",
  },
  {
    name: "includes",
    signature: ".includes(val)",
    description: "Check if contains",
    type: "method",
    insertText: ".includes('value')",
  },
  {
    name: "indexOf",
    signature: ".indexOf(val)",
    description: "Find index",
    type: "method",
    insertText: ".indexOf('value')",
  },
  {
    name: "length",
    signature: ".length",
    description: "Get length",
    type: "method",
    insertText: ".length",
  },
  {
    name: "toLowerCase",
    signature: ".toLowerCase()",
    description: "To lowercase",
    type: "method",
    insertText: ".toLowerCase()",
  },
  {
    name: "toUpperCase",
    signature: ".toUpperCase()",
    description: "To uppercase",
    type: "method",
    insertText: ".toUpperCase()",
  },
  {
    name: "trim",
    signature: ".trim()",
    description: "Remove whitespace",
    type: "method",
    insertText: ".trim()",
  },
  {
    name: "split",
    signature: ".split(sep)",
    description: "Split to array",
    type: "method",
    insertText: ".split(',')",
  },
  {
    name: "replace",
    signature: ".replace(a, b)",
    description: "Replace text",
    type: "method",
    insertText: ".replace('old', 'new')",
  },
  {
    name: "startsWith",
    signature: ".startsWith(s)",
    description: "Check prefix",
    type: "method",
    insertText: ".startsWith('prefix')",
  },
  {
    name: "endsWith",
    signature: ".endsWith(s)",
    description: "Check suffix",
    type: "method",
    insertText: ".endsWith('suffix')",
  },
];

export const BUILTINS: Suggestion[] = [
  {
    name: "head",
    signature: ".head()",
    description: "First element",
    type: "builtin",
    insertText: ".head()",
  },
  {
    name: "last",
    signature: ".last()",
    description: "Last element",
    type: "builtin",
    insertText: ".last()",
  },
  {
    name: "tail",
    signature: ".tail()",
    description: "All but first",
    type: "builtin",
    insertText: ".tail()",
  },
  {
    name: "take",
    signature: ".take(n)",
    description: "First n elements",
    type: "builtin",
    insertText: ".take(5)",
  },
  {
    name: "drop",
    signature: ".drop(n)",
    description: "Skip first n",
    type: "builtin",
    insertText: ".drop(5)",
  },
  {
    name: "uniq",
    signature: ".uniq()",
    description: "Remove duplicates",
    type: "builtin",
    insertText: ".uniq()",
  },
  {
    name: "flatten",
    signature: ".flatten()",
    description: "Flatten nested",
    type: "builtin",
    insertText: ".flatten()",
  },
  {
    name: "compact",
    signature: ".compact()",
    description: "Remove falsy",
    type: "builtin",
    insertText: ".compact()",
  },
  {
    name: "chunk",
    signature: ".chunk(n)",
    description: "Split into chunks",
    type: "builtin",
    insertText: ".chunk(3)",
  },
  {
    name: "groupBy",
    signature: ".groupBy(fn)",
    description: "Group by key",
    type: "builtin",
    insertText: ".groupBy(x => x)",
  },
  {
    name: "sortBy",
    signature: ".sortBy(fn)",
    description: "Sort by key",
    type: "builtin",
    insertText: ".sortBy(x => x)",
  },
  {
    name: "pluck",
    signature: ".pluck(key)",
    description: "Extract property",
    type: "builtin",
    insertText: ".pluck('name')",
  },
  {
    name: "sum",
    signature: ".sum()",
    description: "Sum numbers",
    type: "builtin",
    insertText: ".sum()",
  },
  {
    name: "mean",
    signature: ".mean()",
    description: "Average",
    type: "builtin",
    insertText: ".mean()",
  },
  {
    name: "min",
    signature: ".min()",
    description: "Minimum value",
    type: "builtin",
    insertText: ".min()",
  },
  {
    name: "max",
    signature: ".max()",
    description: "Maximum value",
    type: "builtin",
    insertText: ".max()",
  },
  {
    name: "keys",
    signature: ".keys()",
    description: "Object keys",
    type: "builtin",
    insertText: ".keys()",
  },
  {
    name: "vals",
    signature: ".vals()",
    description: "Object values",
    type: "builtin",
    insertText: ".vals()",
  },
  {
    name: "pick",
    signature: ".pick(k1, k2)",
    description: "Pick keys",
    type: "builtin",
    insertText: ".pick('key')",
  },
  {
    name: "omit",
    signature: ".omit(k1, k2)",
    description: "Omit keys",
    type: "builtin",
    insertText: ".omit('key')",
  },
  {
    name: "merge",
    signature: ".merge(obj)",
    description: "Merge objects",
    type: "builtin",
    insertText: ".merge({})",
  },
  {
    name: "len",
    signature: ".len()",
    description: "Get length",
    type: "builtin",
    insertText: ".len()",
  },
  {
    name: "type",
    signature: ".type()",
    description: "Get type",
    type: "builtin",
    insertText: ".type()",
  },
  {
    name: "isEmpty",
    signature: ".isEmpty()",
    description: "Check if empty",
    type: "builtin",
    insertText: ".isEmpty()",
  },
];

export const SHORTCUTS: Suggestion[] = [
  {
    name: "mp",
    signature: ".mp(x => ...)",
    description: "map shortcut",
    type: "shortcut",
    insertText: ".mp(x => x)",
  },
  {
    name: "flt",
    signature: ".flt(x => ...)",
    description: "filter shortcut",
    type: "shortcut",
    insertText: ".flt(x => x)",
  },
  {
    name: "fnd",
    signature: ".fnd(x => ...)",
    description: "find shortcut",
    type: "shortcut",
    insertText: ".fnd(x => x)",
  },
  {
    name: "rd",
    signature: ".rd((a,x) => ..., init)",
    description: "reduce shortcut",
    type: "shortcut",
    insertText: ".rd((a, x) => a, 0)",
  },
  {
    name: "kys",
    signature: ".kys",
    description: "keys shortcut",
    type: "shortcut",
    insertText: ".kys",
  },
  {
    name: "vls",
    signature: ".vls",
    description: "values shortcut",
    type: "shortcut",
    insertText: ".vls",
  },
  {
    name: "lc",
    signature: ".lc()",
    description: "toLowerCase shortcut",
    type: "shortcut",
    insertText: ".lc()",
  },
  {
    name: "uc",
    signature: ".uc()",
    description: "toUpperCase shortcut",
    type: "shortcut",
    insertText: ".uc()",
  },
  {
    name: "trm",
    signature: ".trm()",
    description: "trim shortcut",
    type: "shortcut",
    insertText: ".trm()",
  },
];

export const ARRAY_SUGGESTIONS = [
  "map",
  "filter",
  "find",
  "reduce",
  "some",
  "every",
  "sort",
  "slice",
  "join",
  "flat",
  "includes",
  "indexOf",
  "length",
  "head",
  "last",
  "tail",
  "take",
  "drop",
  "uniq",
  "flatten",
  "compact",
  "chunk",
  "groupBy",
  "sortBy",
  "pluck",
  "sum",
  "mean",
  "min",
  "max",
] as const;

export const STRING_SUGGESTIONS = [
  "toLowerCase",
  "toUpperCase",
  "trim",
  "split",
  "replace",
  "startsWith",
  "endsWith",
  "includes",
  "length",
  "type",
  "isEmpty",
] as const;

export const OBJECT_SUGGESTIONS = [
  "keys",
  "vals",
  "pick",
  "omit",
  "merge",
  "len",
  "type",
  "isEmpty",
] as const;

export const NUMBER_SUGGESTIONS = ["toString", "toFixed", "type"] as const;

export const ALL_SUGGESTIONS: Suggestion[] = [...METHODS, ...BUILTINS, ...SHORTCUTS];
