export const CLI_FLAGS = [
  { long: "--help", short: "-h", description: "Show help" },
  { long: "--version", short: "-v", description: "Show version" },
  { long: "--raw", short: "-r", description: "Output raw strings without quotes" },
  { long: "--pretty", short: "-p", description: "Pretty print output with indentation" },
  { long: "--compact", short: "-c", description: "Output compact JSON (no whitespace)" },
  { long: "--type", short: "-t", description: "Show the type of the result" },
  { long: "--format", short: null, description: "Output format: json, yaml, csv, table" },
  { long: "--input-format", short: "-if", description: "Input format: json, yaml, toml, csv, tsv, lines, text" },
  { long: "--detect", short: null, description: "Show detected input format without processing" },
  { long: "--list", short: "-l", description: "List files in directory" },
  { long: "--grep", short: "-g", description: "Search for pattern in files" },
  { long: "--find", short: "-f", description: "Path to search in" },
  { long: "--recursive", short: "-R", description: "Recursive search" },
  { long: "--ignore-case", short: "-i", description: "Case insensitive search" },
  { long: "--line-numbers", short: "-n", description: "Show line numbers" },
  { long: "--ext", short: null, description: "Filter by file extensions" },
  { long: "--max-depth", short: null, description: "Maximum recursion depth" },
  { long: "--shortcuts", short: null, description: "Show all available shortcuts" },
  { long: "--shorten", short: null, description: "Convert expression to shorthand" },
  { long: "--expand", short: null, description: "Convert shorthand to full form" },
  { long: "--strict", short: "-s", description: "Strict mode" },
  { long: "--slurp", short: "-S", description: "Read all inputs into array" },
  { long: "--null-input", short: "-N", description: "Use null as input" },
  { long: "--interactive", short: null, description: "Interactive mode" },
] as const;

export const JSON_PATH_PATTERNS = [
  { pattern: ".", description: "Root object" },
  { pattern: ".[]", description: "All array elements" },
  { pattern: "..", description: "Recursive descent" },
  { pattern: ".{keys}", description: "Object keys" },
  { pattern: ".{values}", description: "Object values" },
  { pattern: ".{entries}", description: "Object entries" },
  { pattern: ".foo?", description: "Optional access" },
  { pattern: ".foo ?? default", description: "Null coalescing" },
] as const;
