name: update deps

on:
  schedule:
    - cron: "0 5 * * 5"

jobs:
  udpate-deps:
    runs-on: ubuntu-latest
    env:
      SOCKET_SECURITY_API_KEY: ${{ secrets.SOCKET_SECURITY_API_KEY }}

    strategy:
      matrix:
        node-version: [26.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Socket Security Check
        if: ${{ env.SOCKET_SECURITY_API_KEY != '' }}
        run: pnpm dlx @socketsecurity/cli ci

      - run: pnpm update
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm test

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PR_CREATE_TOKEN }}
          commit-message: Update dependencies
          title: "[Codependence]  update dependencies"
          body: |
            ## Dependency updates
            Auto-generated by [codependence][1] using [create-pull-request][2]
            [1]: https://github.com/yowainwright/1ls
            [2]: https://github.com/peter-evans/create-pull-request
          branch: update-dependencies
          labels: codependencies
