import type { ShortcutMapping } from "./types";

export const REGEX_SPECIAL_CHARS = /[.*+?^${}()|[\]\\]/g;

export const IMPLICIT_PROP = {
  PARAM: "x",
  METHOD_WITH_ARGS: /\.(\w+)\(([^)]+)\)/g,
  PROPERTY_ACCESS: /(?<=[(,\s&|><=!+\-*/%])\.([a-zA-Z_]\w*)/g,
  PROPERTY_AT_START: /^\s*\.([a-zA-Z_]\w*)/,
  PROPERTY_AFTER_OPERATOR: /[,\s&|><=!+\-*/%]\.([a-zA-Z_]\w*)/,
  EXPAND_AT_START: /^(\s*)\.([a-zA-Z_]\w*)/,
  EXPAND_AFTER_OPERATOR: /([,\s&|><=!+\-*/%])\.([a-zA-Z_]\w*)/g,
  ARROW_FUNC: /\.(\w+)\((\w+)\s*=>\s*([^)]+)\)/g,
  PARAM_DOT_TEMPLATE: "(?<![a-zA-Z0-9_])PARAM\\.",
} as const;

export const BUILTIN_SHORTCUTS: ShortcutMapping[] = [
  { short: "hd", full: "head", description: "First element", type: "builtin" },
  { short: "lst", full: "last", description: "Last element", type: "builtin" },
  { short: "tl", full: "tail", description: "All but first", type: "builtin" },
  { short: "tk", full: "take", description: "Take n elements", type: "builtin" },
  { short: "drp", full: "drop", description: "Drop n elements", type: "builtin" },
  { short: "unq", full: "uniq", description: "Unique values", type: "builtin" },
  {
    short: "fltn",
    full: "flatten",
    description: "Flatten nested",
    type: "builtin",
  },
  {
    short: "grpBy",
    full: "groupBy",
    description: "Group by key",
    type: "builtin",
  },
  {
    short: "srtBy",
    full: "sortBy",
    description: "Sort by key",
    type: "builtin",
  },
  {
    short: "chnk",
    full: "chunk",
    description: "Split into chunks",
    type: "builtin",
  },
  {
    short: "cmpct",
    full: "compact",
    description: "Remove falsy",
    type: "builtin",
  },
  { short: "pk", full: "pick", description: "Pick keys", type: "builtin" },
  { short: "omt", full: "omit", description: "Omit keys", type: "builtin" },
  { short: "ks", full: "keys", description: "Object keys", type: "builtin" },
  { short: "mrg", full: "merge", description: "Merge objects", type: "builtin" },
  {
    short: "dMrg",
    full: "deepMerge",
    description: "Deep merge",
    type: "builtin",
  },
  {
    short: "frPrs",
    full: "fromPairs",
    description: "Pairs to object",
    type: "builtin",
  },
  {
    short: "toPrs",
    full: "toPairs",
    description: "Object to pairs",
    type: "builtin",
  },
  { short: "avg", full: "mean", description: "Average value", type: "builtin" },
  { short: "cnt", full: "count", description: "Count items", type: "builtin" },
  {
    short: "emp",
    full: "isEmpty",
    description: "Check if empty",
    type: "builtin",
  },
  { short: "nil", full: "isNil", description: "Check if nil", type: "builtin" },
  {
    short: "plk",
    full: "pluck",
    description: "Pluck property",
    type: "builtin",
  },
  { short: "typ", full: "type", description: "Get type", type: "builtin" },
  {
    short: "rng",
    full: "range",
    description: "Generate range",
    type: "builtin",
  },
  { short: "hs", full: "has", description: "Has key", type: "builtin" },
  { short: "nth", full: "nth", description: "Nth element", type: "builtin" },
  {
    short: "ctns",
    full: "contains",
    description: "Contains value",
    type: "builtin",
  },
  { short: "add", full: "add", description: "Add/concat", type: "builtin" },
  { short: "pth", full: "path", description: "All paths", type: "builtin" },
  {
    short: "gpth",
    full: "getpath",
    description: "Get at path",
    type: "builtin",
  },
  {
    short: "spth",
    full: "setpath",
    description: "Set at path",
    type: "builtin",
  },
  { short: "rec", full: "recurse", description: "Recurse all", type: "builtin" },
  { short: "spl", full: "split", description: "Split string", type: "builtin" },
  { short: "jn", full: "join", description: "Join array", type: "builtin" },
  {
    short: "stw",
    full: "startswith",
    description: "Starts with",
    type: "builtin",
  },
  {
    short: "edw",
    full: "endswith",
    description: "Ends with",
    type: "builtin",
  },
  {
    short: "ltrm",
    full: "ltrimstr",
    description: "Trim prefix",
    type: "builtin",
  },
  {
    short: "rtrm",
    full: "rtrimstr",
    description: "Trim suffix",
    type: "builtin",
  },
  {
    short: "tstr",
    full: "tostring",
    description: "To string",
    type: "builtin",
  },
  {
    short: "tnum",
    full: "tonumber",
    description: "To number",
    type: "builtin",
  },
  { short: "flr", full: "floor", description: "Floor number", type: "builtin" },
  { short: "cl", full: "ceil", description: "Ceil number", type: "builtin" },
  { short: "rnd", full: "round", description: "Round number", type: "builtin" },
  {
    short: "abs",
    full: "abs",
    description: "Absolute value",
    type: "builtin",
  },
  {
    short: "sel",
    full: "select",
    description: "Filter by predicate",
    type: "builtin",
  },
  { short: "dbg", full: "debug", description: "Debug output", type: "builtin" },
];

export const SHORTCUTS: ShortcutMapping[] = [
  {
    short: ".mp",
    full: ".map",
    description: "Transform each element",
    type: "array",
  },
  {
    short: ".flt",
    full: ".filter",
    description: "Filter elements",
    type: "array",
  },
  {
    short: ".rd",
    full: ".reduce",
    description: "Reduce to single value",
    type: "array",
  },
  {
    short: ".fnd",
    full: ".find",
    description: "Find first match",
    type: "array",
  },
  {
    short: ".fndIdx",
    full: ".findIndex",
    description: "Find index of first match",
    type: "array",
  },
  {
    short: ".sm",
    full: ".some",
    description: "Test if any match",
    type: "array",
  },
  {
    short: ".evr",
    full: ".every",
    description: "Test if all match",
    type: "array",
  },
  { short: ".srt", full: ".sort", description: "Sort elements", type: "array" },
  {
    short: ".rvs",
    full: ".reverse",
    description: "Reverse order",
    type: "array",
  },
  { short: ".jn", full: ".join", description: "Join to string", type: "array" },
  {
    short: ".slc",
    full: ".slice",
    description: "Extract portion",
    type: "array",
  },
  {
    short: ".splt",
    full: ".split",
    description: "Split string to array",
    type: "string",
  },
  { short: ".psh", full: ".push", description: "Add to end", type: "array" },
  { short: ".pp", full: ".pop", description: "Remove from end", type: "array" },
  {
    short: ".shft",
    full: ".shift",
    description: "Remove from start",
    type: "array",
  },
  {
    short: ".unshft",
    full: ".unshift",
    description: "Add to start",
    type: "array",
  },
  {
    short: ".fltMap",
    full: ".flatMap",
    description: "Map and flatten",
    type: "array",
  },
  {
    short: ".flt1",
    full: ".flat",
    description: "Flatten array",
    type: "array",
  },
  {
    short: ".incl",
    full: ".includes",
    description: "Check if includes",
    type: "array",
  },
  {
    short: ".idxOf",
    full: ".indexOf",
    description: "Find index",
    type: "array",
  },
  {
    short: ".kys",
    full: ".{keys}",
    description: "Get object keys",
    type: "object",
  },
  {
    short: ".vls",
    full: ".{values}",
    description: "Get object values",
    type: "object",
  },
  {
    short: ".ents",
    full: ".{entries}",
    description: "Get object entries",
    type: "object",
  },
  {
    short: ".len",
    full: ".{length}",
    description: "Get length/size",
    type: "object",
  },
  {
    short: ".lc",
    full: ".toLowerCase",
    description: "Convert to lowercase",
    type: "string",
  },
  {
    short: ".uc",
    full: ".toUpperCase",
    description: "Convert to uppercase",
    type: "string",
  },
  {
    short: ".trm",
    full: ".trim",
    description: "Remove whitespace",
    type: "string",
  },
  {
    short: ".trmSt",
    full: ".trimStart",
    description: "Remove leading whitespace",
    type: "string",
  },
  {
    short: ".trmEnd",
    full: ".trimEnd",
    description: "Remove trailing whitespace",
    type: "string",
  },
  {
    short: ".rpl",
    full: ".replace",
    description: "Replace text",
    type: "string",
  },
  {
    short: ".rplAll",
    full: ".replaceAll",
    description: "Replace all occurrences",
    type: "string",
  },
  {
    short: ".pdSt",
    full: ".padStart",
    description: "Pad start",
    type: "string",
  },
  { short: ".pdEnd", full: ".padEnd", description: "Pad end", type: "string" },
  {
    short: ".stsWith",
    full: ".startsWith",
    description: "Check if starts with",
    type: "string",
  },
  {
    short: ".endsWith",
    full: ".endsWith",
    description: "Check if ends with",
    type: "string",
  },
  {
    short: ".sbstr",
    full: ".substring",
    description: "Extract substring",
    type: "string",
  },
  {
    short: ".chr",
    full: ".charAt",
    description: "Get character at index",
    type: "string",
  },
  {
    short: ".chrCd",
    full: ".charCodeAt",
    description: "Get character code",
    type: "string",
  },
  {
    short: ".mtch",
    full: ".match",
    description: "Match pattern",
    type: "string",
  },
  {
    short: ".str",
    full: ".toString",
    description: "Convert to string",
    type: "any",
  },
  {
    short: ".json",
    full: ".toJSON",
    description: "Convert to JSON",
    type: "any",
  },
  {
    short: ".val",
    full: ".valueOf",
    description: "Get primitive value",
    type: "any",
  },
];
